package com.shnupbups.taglib;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.tag.Tag;

public class CommonTags implements TagNamespace {
	public static final CommonTags INSTANCE = new CommonTags();

	public static final Tag<Block> AIR = INSTANCE.getBlockTag("air");
	public static final Tag<Block> BEACON_PYRAMIDS = INSTANCE.getBlockTag("beacon_pyramids");
	public static final Tag<Block> CLIMBABLE = INSTANCE.getBlockTag("climbable");
	public static final Tag<Block> COBBLESTONE = INSTANCE.getBlockTag("cobblestone");
	public static final Tag<Block> COMMAND_BLOCKS = INSTANCE.getBlockTag("command_blocks");
	public static final Tag<Block> CONCRETE = INSTANCE.getBlockTag("concrete");
	public static final Tag<Block> CONRETE_POWDERS = INSTANCE.getBlockTag("concrete_powders");
	public static final Tag<Block> CORAL_FANS = INSTANCE.getBlockTag("coral_fans");
	public static final Tag<Block> DEAD_CORAL_BLOCKS = INSTANCE.getBlockTag("dead_coal_blocks");
	public static final Tag<Block> DEAD_CORAL_FANS = INSTANCE.getBlockTag("dead_coral_fans");
	public static final Tag<Block> DEAD_CORAL_PLANTS = INSTANCE.getBlockTag("dead_coral_plants");
	public static final Tag<Block> DEAD_CORALS = INSTANCE.getBlockTag("dead_corals");
	public static final Tag<Block> DEAD_FLOOR_CORAL_FANS = INSTANCE.getBlockTag("dead_floor_coral_fans");
	public static final Tag<Block> DEAD_WALL_CORAL_FANS = INSTANCE.getBlockTag("dead_wall_coral_fans");
	public static final Tag<Block> END_ORES = INSTANCE.getBlockTag("end_ores");
	public static final Tag<Block> ETERNALLY_FLAMMABLE = INSTANCE.getBlockTag("eternally_flammable");
	public static final Tag<Block> FENCE_GATES = INSTANCE.getBlockTag("fence_gates");
	public static final Tag<Block> FLOOR_CORAL_FANS = INSTANCE.getBlockTag("floor_coral_fans");
	public static final Tag<Block> GIANT_MUSHROOM_BLOCKS = INSTANCE.getBlockTag("giant_mushroom_blocks");
	public static final Tag<Block> GLASS = INSTANCE.getBlockTag("glass");
	public static final Tag<Block> GLASS_PANES = INSTANCE.getBlockTag("glass_panes");
	public static final Tag<Block> GLAZED_TERRACOTTA = INSTANCE.getBlockTag("glazed_terracotta");
	public static final Tag<Block> GOURDS = INSTANCE.getBlockTag("gourds");
	public static final Tag<Block> GRAVITY_AFFECTED = INSTANCE.getBlockTag("gravity_affected");
	public static final Tag<Block> HEADS = INSTANCE.getBlockTag("heads");
	public static final Tag<Block> INFESTED_BLOCKS = INSTANCE.getBlockTag("infested_blocks");
	public static final Tag<Block> LADDERS = INSTANCE.getBlockTag("ladders");
	public static final Tag<Block> MUSHROOMS = INSTANCE.getBlockTag("mushrooms");
	public static final Tag<Block> NETHER_BRICKS = INSTANCE.getBlockTag("nether_bricks");
	public static final Tag<Block> NETHER_ORES = INSTANCE.getBlockTag("nether_ores");
	public static final Tag<Block> ORES = INSTANCE.getBlockTag("ores");
	public static final Tag<Block> OVERWORLD_ORES = INSTANCE.getBlockTag("overworld_ores");
	public static final Tag<Block> PISTONS = INSTANCE.getBlockTag("pistons");
	public static final Tag<Block> PORTALS = INSTANCE.getBlockTag("portals");
	public static final Tag<Block> PRESSURE_PLATES = INSTANCE.getBlockTag("pressure_plates");
	public static final Tag<Block> PRISMARINE_BLOCKS = INSTANCE.getBlockTag("prismarine_blocks");
	public static final Tag<Block> PUMPKINS = INSTANCE.getBlockTag("pumpkins");
	public static final Tag<Block> PURPUR_BLOCKS = INSTANCE.getBlockTag("purpur_blocks");
	public static final Tag<Block> QUARTZ_BLOCKS = INSTANCE.getBlockTag("quartz_blocks");
	public static final Tag<Block> RED_SANDSTONE = INSTANCE.getBlockTag("red_sandstone");
	public static final Tag<Block> REDSTONE_TORCH = INSTANCE.getBlockTag("redstone_torch");
	public static final Tag<Block> SANDSTONE = INSTANCE.getBlockTag("sandstone");
	public static final Tag<Block> SANDSTONES = INSTANCE.getBlockTag("sandstones");
	public static final Tag<Block> SNOW = INSTANCE.getBlockTag("snow");
	public static final Tag<Block> SPONGES = INSTANCE.getBlockTag("sponges");
	public static final Tag<Block> STAINED_GLASS = INSTANCE.getBlockTag("stained_glass");
	public static final Tag<Block> STAINED_GLASS_PANES = INSTANCE.getBlockTag("stained_glass_panes");
	public static final Tag<Block> STAINED_TERRACOTTA = INSTANCE.getBlockTag("stained_terracotta");
	public static final Tag<Block> STONE_BRICKS = INSTANCE.getBlockTag("stone_bricks");
	public static final Tag<Block> TERRACOTTA = INSTANCE.getBlockTag("terracotta");
	public static final Tag<Block> TORCH = INSTANCE.getBlockTag("torch");
	public static final Tag<Block> TORCHES = INSTANCE.getBlockTag("torches");
	public static final Tag<Block> TRAPDOORS = INSTANCE.getBlockTag("trapdoors");
	public static final Tag<Block> TULIPS = INSTANCE.getBlockTag("tulips");
	public static final Tag<Block> VINES = INSTANCE.getBlockTag("vines");
	public static final Tag<Block> WALL_CORAL_FANS = INSTANCE.getBlockTag("wall_coral_fans");
	public static final Tag<Block> WOODEN_FENCE_GATES = INSTANCE.getBlockTag("wooden_fence_gates");
	
	public static final Tag<Item> APPLES = INSTANCE.getItemTag("apples");
	public static final Tag<Item> BANNER_PATTERNS = INSTANCE.getItemTag("banner_patterns");
	public static final Tag<Item> BEACON_PAYMENTS = INSTANCE.getItemTag("beacon_payments");
	public static final Tag<Item> BOATS = INSTANCE.getItemTag("boats");
	public static final Tag<Item> BOOKS = INSTANCE.getItemTag("books");
	public static final Tag<Item> BOTTLES = INSTANCE.getItemTag("bottles");
	public static final Tag<Item> BUCKETS = INSTANCE.getItemTag("buckets");
	public static final Tag<Item> COBBLESTONE_ITEM = INSTANCE.getItemTag("cobblestone");
	public static final Tag<Item> COMMAND_BLOCKS_ITEM = INSTANCE.getItemTag("command_blocks");
	public static final Tag<Item> CONCRETE_ITEM = INSTANCE.getItemTag("concrete");
	public static final Tag<Item> CONCRETE_POWDERS_ITEM = INSTANCE.getItemTag("concrete_powders");
	public static final Tag<Item> CORAL_FANS_ITEM = INSTANCE.getItemTag("coral_fans");
	public static final Tag<Item> DEAD_CORAL_BLOCKS_ITEM = INSTANCE.getItemTag("dead_coal_blocks");
	public static final Tag<Item> DEAD_CORAL_FANS_ITEM = INSTANCE.getItemTag("dead_coral_fans");
	public static final Tag<Item> DEAD_CORAL_PLANTS_ITEM = INSTANCE.getItemTag("dead_coral_plants");
	public static final Tag<Item> DEAD_CORALS_ITEM = INSTANCE.getItemTag("dead_corals");
	public static final Tag<Item> DEAD_FLOOR_CORAL_FANS_ITEM = INSTANCE.getItemTag("dead_floor_coral_fans");
	public static final Tag<Item> DEAD_WALL_CORAL_FANS_ITEM = INSTANCE.getItemTag("dead_wall_coral_fans");
	public static final Tag<Item> DYES = INSTANCE.getItemTag("dyes");
	public static final Tag<Item> EMPTY_BOTTLES = INSTANCE.getItemTag("empty_bottles");
	public static final Tag<Item> EMPTY_BUCKETS = INSTANCE.getItemTag("empty_buckets");
	public static final Tag<Item> END_ORES_ITEM = INSTANCE.getItemTag("end_ores");
	public static final Tag<Item> EPIC = INSTANCE.getItemTag("epic");
	public static final Tag<Item> FEATHERS = INSTANCE.getItemTag("feathers");
	public static final Tag<Item> FENCE_GATES_ITEM = INSTANCE.getItemTag("fence_gates");
	public static final Tag<Item> FILLED_BOTTLES = INSTANCE.getItemTag("filled_bottles");
	public static final Tag<Item> FILLED_BUCKETS = INSTANCE.getItemTag("filled_buckets");
	public static final Tag<Item> FIRE_STARTERS = INSTANCE.getItemTag("fire_starters");
	public static final Tag<Item> FISH_BUCKETS = INSTANCE.getItemTag("fish_buckets");
	public static final Tag<Item> FLOOR_CORAL_FANS_ITEM = INSTANCE.getItemTag("floor_coral_fans");
	public static final Tag<Item> GIANT_MUSHROOM_BLOCKS_ITEM = INSTANCE.getItemTag("giant_mushroom_blocks");
	public static final Tag<Item> GLASS_ITEM = INSTANCE.getItemTag("glass");
	public static final Tag<Item> GLASS_PANES_ITEM = INSTANCE.getItemTag("glass_panes");
	public static final Tag<Item> GLAZED_TERRACOTTA_ITEM = INSTANCE.getItemTag("glazed_terracotta");
	public static final Tag<Item> GOLDEN_APPLES = INSTANCE.getItemTag("golden_apples");
	public static final Tag<Item> GOLDEN_FOOD = INSTANCE.getItemTag("golden_food");
	public static final Tag<Item> GOURDS_ITEM = INSTANCE.getItemTag("gourds");
	public static final Tag<Item> HEADS_ITEM = INSTANCE.getItemTag("heads");
	public static final Tag<Item> HORSE_ARMOR = INSTANCE.getItemTag("horse_armor");
	public static final Tag<Item> INFESTED_BLOCKS_ITEM = INSTANCE.getItemTag("infested_blocks");
	public static final Tag<Item> INGOTS = INSTANCE.getItemTag("ingots");
	public static final Tag<Item> LADDERS_ITEM = INSTANCE.getItemTag("ladders");
	public static final Tag<Item> MAPS = INSTANCE.getItemTag("maps");
	public static final Tag<Item> MUSHROOMS_ITEM = INSTANCE.getItemTag("mushrooms");
	public static final Tag<Item> MUSIC_DISCS = INSTANCE.getItemTag("music_discs");
	public static final Tag<Item> NETHER_BRICKS_ITEM = INSTANCE.getItemTag("nether_bricks");
	public static final Tag<Item> NETHER_ORES_ITEM = INSTANCE.getItemTag("nether_ores");
	public static final Tag<Item> NUGGETS = INSTANCE.getItemTag("nuggets");
	public static final Tag<Item> ORES_ITEM = INSTANCE.getItemTag("ores");
	public static final Tag<Item> OVERWORLD_ORES_ITEM = INSTANCE.getItemTag("overworld_ores");
	public static final Tag<Item> PISTONS_ITEM = INSTANCE.getItemTag("pistons");
	public static final Tag<Item> POTIONS = INSTANCE.getItemTag("potions");
	public static final Tag<Item> PRESSURE_PLATES_ITEM = INSTANCE.getItemTag("pressure_plates");
	public static final Tag<Item> PRISMARINE_BLOCKS_ITEM = INSTANCE.getItemTag("prismarine_blocks");
	public static final Tag<Item> PRISMARINE_ITEMS = INSTANCE.getItemTag("prismarine_items");
	public static final Tag<Item> PUMPKINS_ITEM = INSTANCE.getItemTag("pumpkins");
	public static final Tag<Item> PURPUR_BLOCKS_ITEM = INSTANCE.getItemTag("purpur_blocks");
	public static final Tag<Item> QUARTZ_BLOCKS_ITEM = INSTANCE.getItemTag("quartz_blocks");
	public static final Tag<Item> RARE = INSTANCE.getItemTag("rare");
	public static final Tag<Item> RAW_FISH = INSTANCE.getItemTag("raw_fish");
	public static final Tag<Item> RED_SANDSTONE_ITEM = INSTANCE.getItemTag("red_sandstone");
	public static final Tag<Item> REDSTONE_TORCH_ITEM = INSTANCE.getItemTag("redstone_torch");
	public static final Tag<Item> SANDSTONE_ITEM = INSTANCE.getItemTag("sandstone");
	public static final Tag<Item> SANDSTONES_ITEM = INSTANCE.getItemTag("sandstones");
	public static final Tag<Item> SHEARS = INSTANCE.getItemTag("shears");
	public static final Tag<Item> SLIMEBALLS = INSTANCE.getItemTag("slimeballs");
	public static final Tag<Item> SNOW_ITEM = INSTANCE.getItemTag("snow");
	public static final Tag<Item> SPAWN_EGGS = INSTANCE.getItemTag("spawn_eggs");
	public static final Tag<Item> SPONGES_ITEM = INSTANCE.getItemTag("sponges");
	public static final Tag<Item> STAINED_GLASS_ITEM = INSTANCE.getItemTag("stained_glass");
	public static final Tag<Item> STAINED_GLASS_PANES_ITEM = INSTANCE.getItemTag("stained_glass_panes");
	public static final Tag<Item> STAINED_TERRACOTTA_ITEM = INSTANCE.getItemTag("stained_terracotta");
	public static final Tag<Item> STEWS = INSTANCE.getItemTag("stews");
	public static final Tag<Item> STICKS = INSTANCE.getItemTag("sticks");
	public static final Tag<Item> STONE_BRICKS_ITEM = INSTANCE.getItemTag("stone_bricks");
	public static final Tag<Item> TERRACOTTA_ITEM = INSTANCE.getItemTag("terracotta");
	public static final Tag<Item> TORCH_ITEM = INSTANCE.getItemTag("torch");
	public static final Tag<Item> TORCHES_ITEM = INSTANCE.getItemTag("torches");
	public static final Tag<Item> TRAPDOORS_ITEM = INSTANCE.getItemTag("trapdoors");
	public static final Tag<Item> TULIPS_ITEM = INSTANCE.getItemTag("tulips");
	public static final Tag<Item> UNCOMMON = INSTANCE.getItemTag("uncommon");
	public static final Tag<Item> VINES_ITEM = INSTANCE.getItemTag("vines");
	public static final Tag<Item> WALL_CORAL_FANS_ITEM = INSTANCE.getItemTag("wall_coral_fans");
	public static final Tag<Item> WOODEN_FENCE_GATES_ITEM = INSTANCE.getItemTag("wooden_fence_gates");
	
	@Override
	public String getNamespace() {
		return "c";
	}
	
	private CommonTags() {}
}
